### ISSUE TITLE
Is rive-react-native project dead?

### ISSUE THREAD

**Issue by arasrezaei** [rive-app/rive-react-native#155]
Hi,
as title says, other platform actively getting updated,
are there any plans for updating this package?

**Comment by jbtheard** [comment]
Maintaining parity with other libraries would be ideal; for instance most of the react hooks aren't available to react-native. Also, that library hasn't been updated since August while others have been very recently.
It does feel like it's not maintain and clearly a red flag when making the decision Rive vs Lottie for RN.
I'd love to see RN be updated to the level of latest React Doc and some crucial bugs fixed.

**Comment by HayesGordon** [comment]
Closing this issue as we're actively working to keep React Native up to date with the Android and iOS runtimes.

But feel free to reopen if there are concerns, or reach out to us on Discord if you have more questions or would like to chat about anything runtime specific: https://discord.com/invite/FGjmaTr
